const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/dhars/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.TEST_URL||'http://127.0.0.1:8002';
await page.request.post(base+'/api/demo/reset');
await page.goto(base,{waitUntil:'networkidle'});
await page.getByText('CONNECTED',{exact:true}).waitFor();
await page.getByRole('button',{name:'Recovery & what-if',exact:true}).click();
await page.locator('#downtime').fill('300');
await page.waitForTimeout(1500);
if(await page.locator('#downtime').inputValue()!=='300')throw Error('Live update overwrote input');
await page.getByRole('button',{name:'Run what-if comparison'}).click();
await page.getByText('SIMULATION ·',{exact:false}).waitFor();
await page.getByRole('button',{name:'Machine details',exact:true}).click();
await page.getByRole('button',{name:'Inject bearing-fault demo'}).click();
await page.getByRole('button',{name:'Alerts & explanations',exact:true}).click();
await page.getByRole('button',{name:'Explain alert',exact:true}).click();
await page.locator('.question-button').first().waitFor();
if(await page.locator('.question-button').count()!==8)throw Error('Eight questions missing');
await page.locator('.question-button').first().click();
await page.locator('.answer').waitFor();
await page.screenshot({path:'data/alerts-desktop.png',fullPage:true});
await page.waitForFunction(async()=>{const d=await(await fetch('/api/dashboard')).json();return d.routes.M4==='M4-BACKUP';},{},{timeout:30000});
await page.getByRole('button',{name:'Line overview',exact:true}).click();
await page.getByText('Workload → M4-BACKUP',{exact:true}).waitFor();
await page.screenshot({path:'data/recovery-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'data/overview-mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
await page.request.post(base+'/api/demo/reset');
await page.setViewportSize({width:1440,height:1000});
await page.getByRole('button',{name:'Line overview',exact:true}).click();
await page.waitForTimeout(1200);
await page.screenshot({path:'data/overview-desktop.png',fullPage:true});
if(errors.length)throw Error(JSON.stringify(errors));
console.log('PASS: live dashboard, form persistence, what-if, fault injection, 8 explanations, automatic route, mobile layout; no browser errors.');
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});

